name: Build and test
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout source code
            uses: actions/checkout@v3
          # - name: Restore cached build directory
          #   id: cache-build-restore
          #   uses: actions/cache@v3
          #   with:
          #     path: build
          #     key: debian-bullseye-${{ hashFiles('CMakeLists.txt') }}
          - name: build
            run: |
              echo "Build source code"
    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: execute tests
          run: |
            echo "execute test"
    deploy:
      needs: [test] 
      uses: bisegni/test-deploy-workflow/.github/workflows/deploy.yml@main
      with:
        deploy-image: "image index"
      secrets: inherit
