name: Build and test
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
    build:
        uses: bisegni/test-deploy-workflow/.github/workflows/build.yml@main
        secrets: inherit

